blueprint:
  name: Set Clock Helper Alternate Timezone to Australia/ACT-Victoria
  description: Sets the clock helper alternate timezone to Australia/ACT-Victoria (AEST-10AEDT,M10.1.0,M4.1.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "AEST-10AEDT,M10.1.0,M4.1.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Australia/ACT-Victoria"
