blueprint:
  name: Set Clock Helper Timezone to Australia/Adelaide-Yancowinna
  description: Sets the clock helper timezone to Australia/Adelaide-Yancowinna (ACST-9:30ACDT,M10.1.0,M4.1.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "ACST-9:30ACDT,M10.1.0,M4.1.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Australia/Adelaide-Yancowinna"
