blueprint:
  name: Set Clock Helper Alternate Timezone to Australia/Brisbane-Queensland
  description: Sets the clock helper alternate timezone to Australia/Brisbane-Queensland (AEST-10)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "AEST-10"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Australia/Brisbane-Queensland"
