blueprint:
  name: Set Clock Helper Timezone to Australia/Darwin-North
  description: Sets the clock helper timezone to Australia/Darwin-North (ACST-9:30)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "ACST-9:30"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Australia/Darwin-North"
