blueprint:
  name: Set Clock Helper Timezone to Australia/LHI-Lord_Howe
  description: Sets the clock helper timezone to Australia/LHI-Lord_Howe (<+1030>-10:30<+11>-11,M10.1.0,M4.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Australia/LHI-Lord_Howe"
