blueprint:
  name: Set Clock Helper Timezone to Indian/Antananarivo-Mayotte
  description: Sets the clock helper timezone to Indian/Antananarivo-Mayotte (EAT-3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "EAT-3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Indian/Antananarivo-Mayotte"
