blueprint:
  name: Set Clock Helper Timezone to Indian/Cocos
  description: Sets the clock helper timezone to Indian/Cocos (<+0630>-6:30)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+0630>-6:30"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Indian/Cocos"
