blueprint:
  name: Set Clock Helper Alternate Timezone to Brazil/DeNoronha
  description: Sets the clock helper alternate timezone to Brazil/DeNoronha (<-02>2)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-02>2"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Brazil/DeNoronha"
