blueprint:
  name: Set Clock Helper Timezone to Brazil/West
  description: Sets the clock helper timezone to Brazil/West (<-04>4)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-04>4"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Brazil/West"
