blueprint:
  name: Set Clock Helper Timezone to Mexico/General
  description: Sets the clock helper timezone to Mexico/General (CST6)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "CST6"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Mexico/General"
