// Auto-generated timezone options for ESPHome
if (x == "Africa/Abidjan-Timbuktu") { id(tzoption) = "GMT0"; }
else if (x == "Africa/Addis_Ababa-Nairobi") { id(tzoption) = "EAT-3"; }
else if (x == "Africa/Algiers-Tunis") { id(tzoption) = "CET-1"; }
else if (x == "Africa/Bangui-Porto-Novo") { id(tzoption) = "WAT-1"; }
else if (x == "Africa/Blantyre-Windhoek") { id(tzoption) = "CAT-2"; }
else if (x == "Africa/Cairo") { id(tzoption) = "EET-2EEST,M4.5.5/0,M10.5.4/24"; }
else if (x == "Africa/Casablanca-El_Aaiun") { id(tzoption) = "<+01>-1"; }
else if (x == "Africa/Ceuta") { id(tzoption) = "CET-1CEST,M3.5.0,M10.5.0/3"; }
else if (x == "Africa/Johannesburg-Mbabane") { id(tzoption) = "SAST-2"; }
else if (x == "Africa/Tripoli") { id(tzoption) = "EET-2"; }
else if (x == "America/Adak-Atka") { id(tzoption) = "HST10HDT,M3.2.0,M11.1.0"; }
else if (x == "America/Anchorage-Yakutat") { id(tzoption) = "AKST9AKDT,M3.2.0,M11.1.0"; }
else if (x == "America/Anguilla-Virgin") { id(tzoption) = "AST4"; }
else if (x == "America/Araguaina-Sao_Paulo") { id(tzoption) = "<-03>3"; }
else if (x == "America/Atikokan-Panama") { id(tzoption) = "EST5"; }
else if (x == "America/Bahia_Banderas-Tegucigalpa") { id(tzoption) = "CST6"; }
else if (x == "America/Boa_Vista-Porto_Velho") { id(tzoption) = "<-04>4"; }
else if (x == "America/Bogota-Rio_Branco") { id(tzoption) = "<-05>5"; }
else if (x == "America/Boise-Yellowknife") { id(tzoption) = "MST7MDT,M3.2.0,M11.1.0"; }
else if (x == "America/Chicago-Winnipeg") { id(tzoption) = "CST6CDT,M3.2.0,M11.1.0"; }
else if (x == "America/Creston-Whitehorse") { id(tzoption) = "MST7"; }
else if (x == "America/Danmarkshavn") { id(tzoption) = "GMT0"; }
else if (x == "America/Detroit-Toronto") { id(tzoption) = "EST5EDT,M3.2.0,M11.1.0"; }
else if (x == "America/Ensenada-Vancouver") { id(tzoption) = "PST8PDT,M3.2.0,M11.1.0"; }
else if (x == "America/Glace_Bay-Thule") { id(tzoption) = "AST4ADT,M3.2.0,M11.1.0"; }
else if (x == "America/Godthab-Scoresbysund") { id(tzoption) = "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"; }
else if (x == "America/Havana") { id(tzoption) = "CST5CDT,M3.2.0/0,M11.1.0/1"; }
else if (x == "America/Miquelon") { id(tzoption) = "<-03>3<-02>,M3.2.0,M11.1.0"; }
else if (x == "America/Noronha") { id(tzoption) = "<-02>2"; }
else if (x == "America/Santiago") { id(tzoption) = "<-04>4<-03>,M9.1.6/24,M4.1.6/24"; }
else if (x == "America/St_Johns") { id(tzoption) = "NST3:30NDT,M3.2.0,M11.1.0"; }
else if (x == "America/Argentina/Buenos_Aires-Ushuaia") { id(tzoption) = "<-03>3"; }
else if (x == "America/Indiana/Indianapolis-Winamac") { id(tzoption) = "EST5EDT,M3.2.0,M11.1.0"; }
else if (x == "America/Indiana/Knox-Tell_City") { id(tzoption) = "CST6CDT,M3.2.0,M11.1.0"; }
else if (x == "America/Kentucky/Louisville-Monticello") { id(tzoption) = "EST5EDT,M3.2.0,M11.1.0"; }
else if (x == "America/North_Dakota/Beulah-New_Salem") { id(tzoption) = "CST6CDT,M3.2.0,M11.1.0"; }
else if (x == "Antarctica/Casey") { id(tzoption) = "<+08>-8"; }
else if (x == "Antarctica/Davis") { id(tzoption) = "<+07>-7"; }
else if (x == "Antarctica/DumontDUrville") { id(tzoption) = "<+10>-10"; }
else if (x == "Antarctica/Macquarie") { id(tzoption) = "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
else if (x == "Antarctica/Mawson-Vostok") { id(tzoption) = "<+05>-5"; }
else if (x == "Antarctica/McMurdo-South_Pole") { id(tzoption) = "NZST-12NZDT,M9.5.0,M4.1.0/3"; }
else if (x == "Antarctica/Palmer-Rothera") { id(tzoption) = "<-03>3"; }
else if (x == "Antarctica/Syowa") { id(tzoption) = "<+03>-3"; }
else if (x == "Antarctica/Troll") { id(tzoption) = "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3"; }
else if (x == "Arctic/Longyearbyen") { id(tzoption) = "CET-1CEST,M3.5.0,M10.5.0/3"; }
else if (x == "Asia/Aden-Riyadh") { id(tzoption) = "<+03>-3"; }
else if (x == "Asia/Almaty-Yekaterinburg") { id(tzoption) = "<+05>-5"; }
else if (x == "Asia/Anadyr-Kamchatka") { id(tzoption) = "<+12>-12"; }
else if (x == "Asia/Baku-Yerevan") { id(tzoption) = "<+04>-4"; }
else if (x == "Asia/Bangkok-Vientiane") { id(tzoption) = "<+07>-7"; }
else if (x == "Asia/Beirut") { id(tzoption) = "EET-2EEST,M3.5.0/0,M10.5.0/0"; }
else if (x == "Asia/Bishkek-Urumqi") { id(tzoption) = "<+06>-6"; }
else if (x == "Asia/Brunei-Ulan_Bator") { id(tzoption) = "<+08>-8"; }
else if (x == "Asia/Calcutta-Kolkata") { id(tzoption) = "IST-5:30"; }
else if (x == "Asia/Chita-Yakutsk") { id(tzoption) = "<+09>-9"; }
else if (x == "Asia/Chongqing-Taipei") { id(tzoption) = "CST-8"; }
else if (x == "Asia/Colombo") { id(tzoption) = "<+0530>-5:30"; }
else if (x == "Asia/Famagusta-Nicosia") { id(tzoption) = "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
else if (x == "Asia/Gaza-Hebron") { id(tzoption) = "EET-2EEST,M3.4.4/50,M10.4.4/50"; }
else if (x == "Asia/Hong_Kong") { id(tzoption) = "HKT-8"; }
else if (x == "Asia/Jakarta-Pontianak") { id(tzoption) = "WIB-7"; }
else if (x == "Asia/Jayapura") { id(tzoption) = "WIT-9"; }
else if (x == "Asia/Jerusalem-Tel_Aviv") { id(tzoption) = "IST-2IDT,M3.4.4/26,M10.5.0"; }
else if (x == "Asia/Kabul") { id(tzoption) = "<+0430>-4:30"; }
else if (x == "Asia/Karachi") { id(tzoption) = "PKT-5"; }
else if (x == "Asia/Kathmandu-Katmandu") { id(tzoption) = "<+0545>-5:45"; }
else if (x == "Asia/Magadan-Srednekolymsk") { id(tzoption) = "<+11>-11"; }
else if (x == "Asia/Makassar-Ujung_Pandang") { id(tzoption) = "WITA-8"; }
else if (x == "Asia/Manila") { id(tzoption) = "PST-8"; }
else if (x == "Asia/Pyongyang-Seoul") { id(tzoption) = "KST-9"; }
else if (x == "Asia/Rangoon-Yangon") { id(tzoption) = "<+0630>-6:30"; }
else if (x == "Asia/Tehran") { id(tzoption) = "<+0330>-3:30"; }
else if (x == "Asia/Tokyo") { id(tzoption) = "JST-9"; }
else if (x == "Asia/Ust-Nera-Vladivostok") { id(tzoption) = "<+10>-10"; }
else if (x == "Atlantic/Azores") { id(tzoption) = "<-01>1<+00>,M3.5.0/0,M10.5.0/1"; }
else if (x == "Atlantic/Bermuda") { id(tzoption) = "AST4ADT,M3.2.0,M11.1.0"; }
else if (x == "Atlantic/Canary-Madeira") { id(tzoption) = "WET0WEST,M3.5.0/1,M10.5.0"; }
else if (x == "Atlantic/Cape_Verde") { id(tzoption) = "<-01>1"; }
else if (x == "Atlantic/Jan_Mayen") { id(tzoption) = "CET-1CEST,M3.5.0,M10.5.0/3"; }
else if (x == "Atlantic/Reykjavik-St_Helena") { id(tzoption) = "GMT0"; }
else if (x == "Atlantic/South_Georgia") { id(tzoption) = "<-02>2"; }
else if (x == "Atlantic/Stanley") { id(tzoption) = "<-03>3"; }
else if (x == "Australia/ACT-Victoria") { id(tzoption) = "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
else if (x == "Australia/Adelaide-Yancowinna") { id(tzoption) = "ACST-9:30ACDT,M10.1.0,M4.1.0/3"; }
else if (x == "Australia/Brisbane-Queensland") { id(tzoption) = "AEST-10"; }
else if (x == "Australia/Darwin-North") { id(tzoption) = "ACST-9:30"; }
else if (x == "Australia/Eucla") { id(tzoption) = "<+0845>-8:45"; }
else if (x == "Australia/LHI-Lord_Howe") { id(tzoption) = "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0"; }
else if (x == "Australia/Perth-West") { id(tzoption) = "AWST-8"; }
else if (x == "Brazil/Acre") { id(tzoption) = "<-05>5"; }
else if (x == "Brazil/DeNoronha") { id(tzoption) = "<-02>2"; }
else if (x == "Brazil/East") { id(tzoption) = "<-03>3"; }
else if (x == "Brazil/West") { id(tzoption) = "<-04>4"; }
else if (x == "Canada/Atlantic") { id(tzoption) = "AST4ADT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Central") { id(tzoption) = "CST6CDT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Eastern") { id(tzoption) = "EST5EDT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Mountain") { id(tzoption) = "MST7MDT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Newfoundland") { id(tzoption) = "NST3:30NDT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Pacific") { id(tzoption) = "PST8PDT,M3.2.0,M11.1.0"; }
else if (x == "Canada/Saskatchewan") { id(tzoption) = "CST6"; }
else if (x == "Canada/Yukon") { id(tzoption) = "MST7"; }
else if (x == "Chile/Continental") { id(tzoption) = "<-04>4<-03>,M9.1.6/24,M4.1.6/24"; }
else if (x == "Chile/EasterIsland") { id(tzoption) = "<-06>6<-05>,M9.1.6/22,M4.1.6/22"; }
else if (x == "Europe/Amsterdam-Zurich") { id(tzoption) = "CET-1CEST,M3.5.0,M10.5.0/3"; }
else if (x == "Europe/Astrakhan-Ulyanovsk") { id(tzoption) = "<+04>-4"; }
else if (x == "Europe/Athens-Zaporozhye") { id(tzoption) = "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
else if (x == "Europe/Belfast-London") { id(tzoption) = "GMT0BST,M3.5.0/1,M10.5.0"; }
else if (x == "Europe/Chisinau-Tiraspol") { id(tzoption) = "EET-2EEST,M3.5.0,M10.5.0/3"; }
else if (x == "Europe/Dublin") { id(tzoption) = "IST-1GMT0,M10.5.0,M3.5.0/1"; }
else if (x == "Europe/Istanbul-Minsk") { id(tzoption) = "<+03>-3"; }
else if (x == "Europe/Kaliningrad") { id(tzoption) = "EET-2"; }
else if (x == "Europe/Kirov-Volgograd") { id(tzoption) = "MSK-3"; }
else if (x == "Europe/Lisbon") { id(tzoption) = "WET0WEST,M3.5.0/1,M10.5.0"; }
else if (x == "Indian/Antananarivo-Mayotte") { id(tzoption) = "EAT-3"; }
else if (x == "Indian/Chagos") { id(tzoption) = "<+06>-6"; }
else if (x == "Indian/Christmas") { id(tzoption) = "<+07>-7"; }
else if (x == "Indian/Cocos") { id(tzoption) = "<+0630>-6:30"; }
else if (x == "Indian/Kerguelen-Maldives") { id(tzoption) = "<+05>-5"; }
else if (x == "Indian/Mahe-Reunion") { id(tzoption) = "<+04>-4"; }
else if (x == "Mexico/BajaNorte") { id(tzoption) = "PST8PDT,M3.2.0,M11.1.0"; }
else if (x == "Mexico/BajaSur") { id(tzoption) = "MST7"; }
else if (x == "Mexico/General") { id(tzoption) = "CST6"; }
else if (x == "Pacific/Apia-Tongatapu") { id(tzoption) = "<+13>-13"; }
else if (x == "Pacific/Auckland") { id(tzoption) = "NZST-12NZDT,M9.5.0,M4.1.0/3"; }
else if (x == "Pacific/Bougainville-Ponape") { id(tzoption) = "<+11>-11"; }
else if (x == "Pacific/Chatham") { id(tzoption) = "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45"; }
else if (x == "Pacific/Chuuk-Yap") { id(tzoption) = "<+10>-10"; }
else if (x == "Pacific/Easter") { id(tzoption) = "<-06>6<-05>,M9.1.6/22,M4.1.6/22"; }
else if (x == "Pacific/Fiji-Wallis") { id(tzoption) = "<+12>-12"; }
else if (x == "Pacific/Galapagos") { id(tzoption) = "<-06>6"; }
else if (x == "Pacific/Gambier") { id(tzoption) = "<-09>9"; }
else if (x == "Pacific/Guam-Saipan") { id(tzoption) = "ChST-10"; }
else if (x == "Pacific/Honolulu-Johnston") { id(tzoption) = "HST10"; }
else if (x == "Pacific/Kiritimati") { id(tzoption) = "<+14>-14"; }
else if (x == "Pacific/Marquesas") { id(tzoption) = "<-0930>9:30"; }
else if (x == "Pacific/Midway-Samoa") { id(tzoption) = "SST11"; }
else if (x == "Pacific/Niue") { id(tzoption) = "<-11>11"; }
else if (x == "Pacific/Norfolk") { id(tzoption) = "<+11>-11<+12>,M10.1.0,M4.1.0/3"; }
else if (x == "Pacific/Palau") { id(tzoption) = "<+09>-9"; }
else if (x == "Pacific/Pitcairn") { id(tzoption) = "<-08>8"; }
else if (x == "Pacific/Rarotonga-Tahiti") { id(tzoption) = "<-10>10"; }
else if (x == "US/Alaska") { id(tzoption) = "AKST9AKDT,M3.2.0,M11.1.0"; }
else if (x == "US/Aleutian") { id(tzoption) = "HST10HDT,M3.2.0,M11.1.0"; }
else if (x == "US/Arizona") { id(tzoption) = "MST7"; }
else if (x == "US/Central-Indiana-Starke") { id(tzoption) = "CST6CDT,M3.2.0,M11.1.0"; }
else if (x == "US/East-Indiana-Michigan") { id(tzoption) = "EST5EDT,M3.2.0,M11.1.0"; }
else if (x == "US/Hawaii") { id(tzoption) = "HST10"; }
else if (x == "US/Mountain") { id(tzoption) = "MST7MDT,M3.2.0,M11.1.0"; }
else if (x == "US/Pacific") { id(tzoption) = "PST8PDT,M3.2.0,M11.1.0"; }
else if (x == "US/Samoa") { id(tzoption) = "SST11"; }
else if (x == "Etc/GMT-Greenwich") { id(tzoption) = "GMT0"; }
else if (x == "Etc/GMT-14") { id(tzoption) = "<+14>-14"; }
else if (x == "Etc/GMT-13") { id(tzoption) = "<+13>-13"; }
else if (x == "Etc/GMT-12") { id(tzoption) = "<+12>-12"; }
else if (x == "Etc/GMT-11") { id(tzoption) = "<+11>-11"; }
else if (x == "Etc/GMT-10") { id(tzoption) = "<+10>-10"; }
else if (x == "Etc/GMT-9") { id(tzoption) = "<+09>-9"; }
else if (x == "Etc/GMT-8") { id(tzoption) = "<+08>-8"; }
else if (x == "Etc/GMT-7") { id(tzoption) = "<+07>-7"; }
else if (x == "Etc/GMT-6") { id(tzoption) = "<+06>-6"; }
else if (x == "Etc/GMT-5") { id(tzoption) = "<+05>-5"; }
else if (x == "Etc/GMT-4") { id(tzoption) = "<+04>-4"; }
else if (x == "Etc/GMT-3") { id(tzoption) = "<+03>-3"; }
else if (x == "Etc/GMT-2") { id(tzoption) = "<+02>-2"; }
else if (x == "Etc/GMT-1") { id(tzoption) = "<+01>-1"; }
else if (x == "Etc/GMT+1") { id(tzoption) = "<-01>1"; }
else if (x == "Etc/GMT+2") { id(tzoption) = "<-02>2"; }
else if (x == "Etc/GMT+3") { id(tzoption) = "<-03>3"; }
else if (x == "Etc/GMT+4") { id(tzoption) = "<-04>4"; }
else if (x == "Etc/GMT+5") { id(tzoption) = "<-05>5"; }
else if (x == "Etc/GMT+6") { id(tzoption) = "<-06>6"; }
else if (x == "Etc/GMT+7") { id(tzoption) = "<-07>7"; }
else if (x == "Etc/GMT+8") { id(tzoption) = "<-08>8"; }
else if (x == "Etc/GMT+9") { id(tzoption) = "<-09>9"; }
else if (x == "Etc/GMT+10") { id(tzoption) = "<-10>10"; }
else if (x == "Etc/GMT+11") { id(tzoption) = "<-11>11"; }
else if (x == "Etc/GMT+12") { id(tzoption) = "<-12>12"; }
else if (x == "Etc/UCT-Zulu") { id(tzoption) = "UTC0"; }
else { id(tzoption) = "UTC0"; }
