blueprint:
  name: Set Clock Helper Timezone to Arctic/Longyearbyen
  description: Sets the clock helper timezone to Arctic/Longyearbyen (CET-1CEST,M3.5.0,M10.5.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "CET-1CEST,M3.5.0,M10.5.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Arctic/Longyearbyen"
