blueprint:
  name: Set Clock Helper Alternate Timezone to Canada/Newfoundland
  description: Sets the clock helper alternate timezone to Canada/Newfoundland (NST3:30NDT,M3.2.0,M11.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "NST3:30NDT,M3.2.0,M11.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Canada/Newfoundland"
