blueprint:
  name: Set Clock Helper Timezone to Canada/Yukon
  description: Sets the clock helper timezone to Canada/Yukon (MST7)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "MST7"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Canada/Yukon"
