blueprint:
  name: Set Clock Helper Alternate Timezone to Europe/Amsterdam-Zurich
  description: Sets the clock helper alternate timezone to Europe/Amsterdam-Zurich (CET-1CEST,M3.5.0,M10.5.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "CET-1CEST,M3.5.0,M10.5.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Europe/Amsterdam-Zurich"
