blueprint:
  name: Set Clock Helper Alternate Timezone to Europe/Athens-Zaporozhye
  description: Sets the clock helper alternate timezone to Europe/Athens-Zaporozhye (EET-2EEST,M3.5.0/3,M10.5.0/4)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "EET-2EEST,M3.5.0/3,M10.5.0/4"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Europe/Athens-Zaporozhye"
