blueprint:
  name: Set Clock Helper Timezone to Europe/Belfast-London
  description: Sets the clock helper timezone to Europe/Belfast-London (GMT0BST,M3.5.0/1,M10.5.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "GMT0BST,M3.5.0/1,M10.5.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Europe/Belfast-London"
