blueprint:
  name: Set Clock Helper Alternate Timezone to Europe/Dublin
  description: Sets the clock helper alternate timezone to Europe/Dublin (IST-1GMT0,M10.5.0,M3.5.0/1)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "IST-1GMT0,M10.5.0,M3.5.0/1"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Europe/Dublin"
