blueprint:
  name: Set Clock Helper Alternate Timezone to Europe/Istanbul-Minsk
  description: Sets the clock helper alternate timezone to Europe/Istanbul-Minsk (<+03>-3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<+03>-3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Europe/Istanbul-Minsk"
