blueprint:
  name: Set Clock Helper Alternate Timezone to Europe/Kirov-Volgograd
  description: Sets the clock helper alternate timezone to Europe/Kirov-Volgograd (MSK-3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "MSK-3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Europe/Kirov-Volgograd"
