blueprint:
  name: Set Clock Helper Alternate Timezone to America/Anchorage-Yakutat
  description: Sets the clock helper alternate timezone to America/Anchorage-Yakutat (AKST9AKDT,M3.2.0,M11.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "AKST9AKDT,M3.2.0,M11.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Anchorage-Yakutat"
