blueprint:
  name: Set Clock Helper Timezone to America/Anguilla-Virgin
  description: Sets the clock helper timezone to America/Anguilla-Virgin (AST4)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "AST4"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to America/Anguilla-Virgin"
