blueprint:
  name: Set Clock Helper Alternate Timezone to America/Araguaina-Sao_Paulo
  description: Sets the clock helper alternate timezone to America/Araguaina-Sao_Paulo (<-03>3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-03>3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Araguaina-Sao_Paulo"
