blueprint:
  name: Set Clock Helper Alternate Timezone to America/Atikokan-Panama
  description: Sets the clock helper alternate timezone to America/Atikokan-Panama (EST5)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "EST5"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Atikokan-Panama"
