blueprint:
  name: Set Clock Helper Alternate Timezone to America/Bahia_Banderas-Tegucigalpa
  description: Sets the clock helper alternate timezone to America/Bahia_Banderas-Tegucigalpa (CST6)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "CST6"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Bahia_Banderas-Tegucigalpa"
