blueprint:
  name: Set Clock Helper Alternate Timezone to America/Bogota-Rio_Branco
  description: Sets the clock helper alternate timezone to America/Bogota-Rio_Branco (<-05>5)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-05>5"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Bogota-Rio_Branco"
