blueprint:
  name: Set Clock Helper Timezone to America/Boise-Yellowknife
  description: Sets the clock helper timezone to America/Boise-Yellowknife (MST7MDT,M3.2.0,M11.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "MST7MDT,M3.2.0,M11.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to America/Boise-Yellowknife"
