blueprint:
  name: Set Clock Helper Timezone to America/Godthab-Scoresbysund
  description: Sets the clock helper timezone to America/Godthab-Scoresbysund (<-02>2<-01>,M3.5.0/-1,M10.5.0/0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to America/Godthab-Scoresbysund"
