blueprint:
  name: Set Clock Helper Alternate Timezone to America/Havana
  description: Sets the clock helper alternate timezone to America/Havana (CST5CDT,M3.2.0/0,M11.1.0/1)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "CST5CDT,M3.2.0/0,M11.1.0/1"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Havana"
