blueprint:
  name: Set Clock Helper Alternate Timezone to America/Miquelon
  description: Sets the clock helper alternate timezone to America/Miquelon (<-03>3<-02>,M3.2.0,M11.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-03>3<-02>,M3.2.0,M11.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to America/Miquelon"
