blueprint:
  name: Set Clock Helper Timezone to America/North_Dakota/Beulah-New_Salem
  description: Sets the clock helper timezone to America/North_Dakota/Beulah-New_Salem (CST6CDT,M3.2.0,M11.1.0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "CST6CDT,M3.2.0,M11.1.0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to America/North_Dakota/Beulah-New_Salem"
