blueprint:
  name: Set Clock Helper Timezone to Asia/Almaty-Yekaterinburg
  description: Sets the clock helper timezone to Asia/Almaty-Yekaterinburg (<+05>-5)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+05>-5"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Almaty-Yekaterinburg"
