blueprint:
  name: Set Clock Helper Timezone to Asia/Anadyr-Kamchatka
  description: Sets the clock helper timezone to Asia/Anadyr-Kamchatka (<+12>-12)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+12>-12"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Anadyr-Kamchatka"
