blueprint:
  name: Set Clock Helper Alternate Timezone to Asia/Baku-Yerevan
  description: Sets the clock helper alternate timezone to Asia/Baku-Yerevan (<+04>-4)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<+04>-4"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Asia/Baku-Yerevan"
