blueprint:
  name: Set Clock Helper Timezone to Asia/Beirut
  description: Sets the clock helper timezone to Asia/Beirut (EET-2EEST,M3.5.0/0,M10.5.0/0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "EET-2EEST,M3.5.0/0,M10.5.0/0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Beirut"
