blueprint:
  name: Set Clock Helper Timezone to Asia/Calcutta-Kolkata
  description: Sets the clock helper timezone to Asia/Calcutta-Kolkata (IST-5:30)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "IST-5:30"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Calcutta-Kolkata"
