blueprint:
  name: Set Clock Helper Timezone to Asia/Chita-Yakutsk
  description: Sets the clock helper timezone to Asia/Chita-Yakutsk (<+09>-9)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+09>-9"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Chita-Yakutsk"
