blueprint:
  name: Set Clock Helper Alternate Timezone to Asia/Gaza-Hebron
  description: Sets the clock helper alternate timezone to Asia/Gaza-Hebron (EET-2EEST,M3.4.4/50,M10.4.4/50)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "EET-2EEST,M3.4.4/50,M10.4.4/50"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Asia/Gaza-Hebron"
