blueprint:
  name: Set Clock Helper Timezone to Asia/Hong_Kong
  description: Sets the clock helper timezone to Asia/Hong_Kong (HKT-8)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "HKT-8"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Hong_Kong"
