blueprint:
  name: Set Clock Helper Timezone to Asia/Jayapura
  description: Sets the clock helper timezone to Asia/Jayapura (WIT-9)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "WIT-9"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Jayapura"
