blueprint:
  name: Set Clock Helper Timezone to Asia/Kabul
  description: Sets the clock helper timezone to Asia/Kabul (<+0430>-4:30)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+0430>-4:30"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Kabul"
