blueprint:
  name: Set Clock Helper Timezone to Asia/Karachi
  description: Sets the clock helper timezone to Asia/Karachi (PKT-5)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "PKT-5"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Karachi"
