blueprint:
  name: Set Clock Helper Alternate Timezone to Asia/Kathmandu-Katmandu
  description: Sets the clock helper alternate timezone to Asia/Kathmandu-Katmandu (<+0545>-5:45)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<+0545>-5:45"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Asia/Kathmandu-Katmandu"
