blueprint:
  name: Set Clock Helper Alternate Timezone to Asia/Makassar-Ujung_Pandang
  description: Sets the clock helper alternate timezone to Asia/Makassar-Ujung_Pandang (WITA-8)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "WITA-8"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Asia/Makassar-Ujung_Pandang"
