blueprint:
  name: Set Clock Helper Alternate Timezone to Asia/Tokyo
  description: Sets the clock helper alternate timezone to Asia/Tokyo (JST-9)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "JST-9"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Asia/Tokyo"
