blueprint:
  name: Set Clock Helper Timezone to Asia/Ust-Nera-Vladivostok
  description: Sets the clock helper timezone to Asia/Ust-Nera-Vladivostok (<+10>-10)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+10>-10"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Asia/Ust-Nera-Vladivostok"
