blueprint:
  name: Set Clock Helper Alternate Timezone to Chile/Continental
  description: Sets the clock helper alternate timezone to Chile/Continental (<-04>4<-03>,M9.1.6/24,M4.1.6/24)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-04>4<-03>,M9.1.6/24,M4.1.6/24"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Chile/Continental"
