blueprint:
  name: Set Clock Helper Timezone to Antarctica/Macquarie
  description: Sets the clock helper timezone to Antarctica/Macquarie (AEST-10AEDT,M10.1.0,M4.1.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "AEST-10AEDT,M10.1.0,M4.1.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Antarctica/Macquarie"
