blueprint:
  name: Set Clock Helper Timezone to Antarctica/Palmer-Rothera
  description: Sets the clock helper timezone to Antarctica/Palmer-Rothera (<-03>3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-03>3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Antarctica/Palmer-Rothera"
