blueprint:
  name: Set Clock Helper Timezone to Atlantic/Azores
  description: Sets the clock helper timezone to Atlantic/Azores (<-01>1<+00>,M3.5.0/0,M10.5.0/1)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-01>1<+00>,M3.5.0/0,M10.5.0/1"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Atlantic/Azores"
