blueprint:
  name: Set Clock Helper Timezone to US/Samoa
  description: Sets the clock helper timezone to US/Samoa (SST11)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "SST11"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to US/Samoa"
