blueprint:
  name: Set Clock Helper Timezone to Etc/GMT+5
  description: Sets the clock helper timezone to Etc/GMT+5 (<-05>5)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-05>5"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Etc/GMT+5"
