blueprint:
  name: Set Clock Helper Alternate Timezone to Etc/GMT+11
  description: Sets the clock helper alternate timezone to Etc/GMT+11 (<-11>11)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<-11>11"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Etc/GMT+11"
