blueprint:
  name: Set Clock Helper Alternate Timezone to Etc/GMT-Greenwich
  description: Sets the clock helper alternate timezone to Etc/GMT-Greenwich (GMT0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "GMT0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Etc/GMT-Greenwich"
