blueprint:
  name: Set Clock Helper Timezone to Etc/GMT-Greenwich
  description: Sets the clock helper timezone to Etc/GMT-Greenwich (GMT0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "GMT0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Etc/GMT-Greenwich"
