blueprint:
  name: Set Clock Helper Timezone to Etc/GMT-2
  description: Sets the clock helper timezone to Etc/GMT-2 (<+02>-2)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+02>-2"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Etc/GMT-2"
