blueprint:
  name: Set Clock Helper Timezone to Etc/GMT-7
  description: Sets the clock helper timezone to Etc/GMT-7 (<+07>-7)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+07>-7"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Etc/GMT-7"
