blueprint:
  name: Set Clock Helper Timezone to Etc/UCT-Zulu
  description: Sets the clock helper timezone to Etc/UCT-Zulu (UTC0)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "UTC0"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Etc/UCT-Zulu"
