blueprint:
  name: Set Clock Helper Alternate Timezone to Africa/Bangui-Porto-Novo
  description: Sets the clock helper alternate timezone to Africa/Bangui-Porto-Novo (WAT-1)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "WAT-1"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Africa/Bangui-Porto-Novo"
