blueprint:
  name: Set Clock Helper Alternate Timezone to Africa/Cairo
  description: Sets the clock helper alternate timezone to Africa/Cairo (EET-2EEST,M4.5.5/0,M10.5.4/24)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "EET-2EEST,M4.5.5/0,M10.5.4/24"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Africa/Cairo"
