blueprint:
  name: Set Clock Helper Alternate Timezone to Africa/Casablanca-El_Aaiun
  description: Sets the clock helper alternate timezone to Africa/Casablanca-El_Aaiun (<+01>-1)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "<+01>-1"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Africa/Casablanca-El_Aaiun"
