blueprint:
  name: Set Clock Helper Timezone to Africa/Johannesburg-Mbabane
  description: Sets the clock helper timezone to Africa/Johannesburg-Mbabane (SAST-2)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "SAST-2"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Africa/Johannesburg-Mbabane"
