blueprint:
  name: Set Clock Helper Alternate Timezone to Africa/Tripoli
  description: Sets the clock helper alternate timezone to Africa/Tripoli (EET-2)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_alternate_timezone
    data:
      value: "EET-2"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Alternate Set to Africa/Tripoli"
