blueprint:
  name: Set Clock Helper Timezone to Pacific/Apia-Tongatapu
  description: Sets the clock helper timezone to Pacific/Apia-Tongatapu (<+13>-13)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<+13>-13"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Apia-Tongatapu"
