blueprint:
  name: Set Clock Helper Timezone to Pacific/Auckland
  description: Sets the clock helper timezone to Pacific/Auckland (NZST-12NZDT,M9.5.0,M4.1.0/3)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "NZST-12NZDT,M9.5.0,M4.1.0/3"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Auckland"
