blueprint:
  name: Set Clock Helper Timezone to Pacific/Galapagos
  description: Sets the clock helper timezone to Pacific/Galapagos (<-06>6)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-06>6"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Galapagos"
