blueprint:
  name: Set Clock Helper Timezone to Pacific/Guam-Saipan
  description: Sets the clock helper timezone to Pacific/Guam-Saipan (ChST-10)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "ChST-10"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Guam-Saipan"
