blueprint:
  name: Set Clock Helper Timezone to Pacific/Honolulu-Johnston
  description: Sets the clock helper timezone to Pacific/Honolulu-Johnston (HST10)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "HST10"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Honolulu-Johnston"
