blueprint:
  name: Set Clock Helper Timezone to Pacific/Niue
  description: Sets the clock helper timezone to Pacific/Niue (<-11>11)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-11>11"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Niue"
