blueprint:
  name: Set Clock Helper Timezone to Pacific/Rarotonga-Tahiti
  description: Sets the clock helper timezone to Pacific/Rarotonga-Tahiti (<-10>10)
  domain: script

sequence:
  - service: input_text.set_value
    target:
      entity_id: input_text.clock_helper_timezone
    data:
      value: "<-10>10"
  - service: persistent_notification.create
    data:
      title: ✅ Timezone Updated
      message: "Clock Helper Timezone Set to Pacific/Rarotonga-Tahiti"
