name: Generate and Gzip Timezones

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install natsort

      - name: Run generator in debug mode
        run: python3 gen_tz.py --json

      - name: Generate timezones.json and csv
        run: |
          python3 ./gen-tz.py --json > timezones.json
          python3 ./gen-tz.py --csv > timezones.csv

      - name: Gzip outputs
        run: |
          gzip -f timezones.json
          gzip -f timezones.csv

      - name: Show contents of current directory
        run: ls -alh

      - name: Commit and push all at once
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add timezones.json timezones.json.gz timezones.csv timezones.csv.gz
          git commit -m "Update timezones JSON and CSV files"
          git push
